import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// localhost:3000/users
const page = () => {
  return <div>Hellow Users</div>;
};

export default page;
